POST http://localhost:3000/defar/createCollection
Content-Type: application/json
 
{
    "email":{"type": "String","required": "true","unique": "true"},   
    "password":{"type": "String","required": "true","unique": "true"},
    "prenom":{"type": "String","required": "false"},
    "nom":{"type": "String","required": "false"},
    "login":{"type": "String","required": "false"},
    "username":{"type": "String","required": "false"}
}
###
POST http://localhost:3000/defar/inserer
Content-Type: application/json
 
{
    "email" : "mor@gmail.com",
    "password" : "bountou",
    "prenom" : "Mor",
    "nom" : "seck",
    "login": "passer",
    "username" : "Mor_Baraya"
}


###
GET http://localhost:3000/defar